import { IoHome } from "react-icons/io5";
import { MdDashboard } from "react-icons/md";
import { IoMdCart } from "react-icons/io";
import { FaClipboardList } from "react-icons/fa";

export const links = [
  {
    name:"Categories",
    icon: <IoHome />,
    key:"categories", 
  },
  {
    name:  "All Template",
    icon: <MdDashboard />,
    key: "menu",
  },
  {
    name: "Cart",
    icon: <IoMdCart />,
    key: "cart",
  },
  {
    name: "Orders",
    icon: <FaClipboardList />,
    key: "order",
  },
];

export const lists = [
  {
    id: 1,
    title: "Boutique",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL001/index.html",
  },
  {
    id: 2,
    title: "Boutique",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL002/index.html",
  },
  {
    id: 3,
    title: "Boutique",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL003/index.html",
  },
  {
    id: 4,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL006/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL006/index.html",
  },
  {
    id: 5,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL007/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL007/index.html",
  },
  {
    id: 6,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL008/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL008/index.html",
  },
  {
    id: 7,
    title: "Yoga Centers",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT050/IBGWTCT050TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT050/IBGWTCT050TMPL001/index.html",
  },
  {
    id: 8,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL009/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL009/index.html",
  },
  {
    id: 9,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL0010/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL0010/index.html",
  },
  {
    id: 10,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL0011/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL0011/index.html",
  },
  {
    id: 11,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL0012/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL0012/index.html",
  },
  {
    id: 12,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL0013/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL0013/index.html",
  },
  {
    id: 13,
    title: "Beauty Salon & Parlour",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL001/index.html",
  },
  {
    id: 14,
    title: "Beauty Salon & Parlour",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL002/index.html",
  },
  {
    id: 15,
    title: "Beauty Salon & Parlour",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL003/index.html",
  },
  {
    id: 16,
    title: "Beauty Salon & Parlour",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL004/index.html",
  },
  {
    id: 17,
    title: "Beauty Salon & Parlour",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT001/IBGWTCT001TMPL005/index.html",
  },
  {
    id: 18,
    title: "Hotels",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL001/index.html",
  },
  {
    id: 19,
    title: "Hotels",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL001/index.html",
  },
  {
    id: 20,
    title: "Hotels",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL003/index.html",
  },
  {
    id: 21,
    title: "Hotels",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL005/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL005/index.html",
  },
  {
    id: 22,
    title: "Restaurants",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL001/index.html",
  },
  {
    id: 23,
    title: "Restaurants",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL006/index.html",
  },
  {
    id: 24,
    title: "Restaurants",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL003/index.html",
  },
  {
    id: 25,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL001/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL001/index.html",
  },
  {
    id: 26,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL002/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL002/index.html",
  },
  {
    id: 27,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL003/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL003/index.html",
  },
  {
    id: 28,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL004/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL004/index.html",
  },
  {
    id: 29,
    title: "Restaurants",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL004/index.html",
  },
  {
    id: 30,
    title: "Restaurants",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT004/IBGWTCT004TMPL005/index.html",
  },
  {
    id: 31,
    title: "Cake Shop",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL001/index.html",
  },
  {
    id: 32,
    title: "Cake Shop",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL002/index.html",
  },
  {
    id: 33,
    title: "Cake Shop",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL003/index.html",
  },
  {
    id: 34,
    title: "Cake Shop",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL004/index.html",
  },
  {
    id: 35,
    title: "Cake Shop",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT005/IBGWTCT005TMPL005/index.html",
  },
  {
    id: 36,
    title: "Icecream Parlour",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT006/IBGWTCT006TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT006/IBGWTCT006TMPL001/index.html",
  },
  {
    id: 37,
    title: "Icecream Parlour",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT006/IBGWTCT006TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT006/IBGWTCT006TMPL002/index.html",
  },

  {
    id: 38,
    title: "Dairy Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL003/index.html",
  },
  {
    id: 39,
    title: "Dairy Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL004/index.html",
  },
  {
    id: 40,
    title: "Dairy Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL005/index.html",
  },
  {
    id: 41,
    title: "Gift Centers",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT008/IBGWTCT008TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT008/IBGWTCT008TMPL001/index.html",
  },
  {
    id: 42,
    title: "Bookey Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL001/index.html",
  },
  {
    id: 43,
    title: "Bookey Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL002/index.html",
  },
  {
    id: 44,
    title: "Bookey Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL003/index.html",
  },
  {
    id: 45,
    title: "Bookey Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL004/index.html",
  },
  {
    id: 46,
    title: "Bookey Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT009/IBGWTCT009TMPL005/index.html",
  },
  {
    id: 47,
    title: "Flowers",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL001/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL001/index.html",
  },
  {
    id: 48,
    title: "Flowers",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL002/index.html",
  },
  {
    id: 49,
    title: "Flowers",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL003/index.html",
  },
  {
    id: 50,
    title: "Flowers",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL004/index.html",
  },
  {
    id: 51,
    title: "Flowers",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT010/IBGWTCT010TMPL005/index.html",
  },
  {
    id: 52,
    title: "Photography",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL001/index.html",
  },
  {
    id: 53,
    title: "Photography",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL002/index.html",
  },
  {
    id: 54,
    title: "Trustee",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL002/index.html",
  },
  {
    id: 55,
    title: "Trustee",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT000/IBGWTCT040TMPL003/index.html",
  },
  {
    id: 56,
    title: "Trustee",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL004/index.html",
  },
  {
    id: 57,
    title: "Trustee",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL005/index.html",
  },
  {
    id: 58,
    title: "Photography",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL003/index.html",
  },
  {
    id: 59,
    title: "Photography",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL008/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL008/index.html",
  },
  {
    id: 60,
    title: "Photography",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT011/IBGWTCT011TMPL006/index.html",
  },
  {
    id: 61,
    title: "Interior Design",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTC012TMPL001/index.html",
  },
  {
    id: 62,
    title: "Interior Design",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL002/index.html",
  },
  {
    id: 63,
    title: "Dairy Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL001/index.html",
  },
  {
    id: 64,
    title: "Dairy Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT007/IBGWTCT007TMPL002/index.html",
  },
  {
    id: 65,
    title: "Interior Design",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL003/index.html",
  },
  {
    id: 66,
    title: "Interior Design",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL004/index.html",
  },
  {
    id: 67,
    title: "Interior Design",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT012/IBGWTCT012TMPL005/index.html",
  },
  {
    id: 68,
    title: "Real Estate",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL001/index.html",
  },
  {
    id: 69,
    title: "Real Estate",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL002/index.html",
  },
  {
    id: 70,
    title: "Real Estate",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL003/index.html",
  },
  {
    id: 71,
    title: "Real Estate",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL004/index.html",
  },
  {
    id: 72,
    title: "Real Estate",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT013/IBGWTCT013TMPL005/index.html",
  },
  {
    id: 73,
    title: "Builder",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL001/index.html",
  },

  {
    id: 74,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL001/index.html",
  },
  {
    id: 75,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL002/index.html",
  },
  {
    id: 76,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL003/index.html",
  },
  {
    id: 77,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL004/index.html",
  },
  {
    id: 78,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT015/IBGWTCT015TMPL005/index.html",
  },
  {
    id: 79,
    title: "Boutique",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL004/index.html",
  },
  {
    id: 80,
    title: "Cafe",
    img: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL005/home.jpg",
    price: "$5.50",
    live: "https://webtekdi.com/website/buynow/templates/IBGWTCT002/IBGWTCT002TMPL005/index.html",
  },
  {
    id: 81,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT016/IBGWTCT016TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT016/IBGWTCT016TMPL001/index.html",
  },
  {
    id: 82,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT016/IBGWTCT016TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT016/IBGWTCT016TMPL002/index.html",
  },
  {
    id: 83,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL001/index.html",
  },
  {
    id: 84,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL002/index.html",
  },
  {
    id: 85,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL003/index.html",
  },
  {
    id: 86,
    title: "Eye Clinic",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT018/IBGWTCT018TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT018/IBGWTCT018TMPL001/index.html",
  },
  {
    id: 87,
    title: "Dental Clinic",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL001/index.html",
  },
  {
    id: 88,
    title: "Dental Clinic",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL002/index.html",
  },
  {
    id: 89,
    title: "Dental Clinic",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL003/index.html",
  },
  {
    id: 90,
    title: "Dental Clinic",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL004/index.html",
  },
  {
    id: 91,
    title: "Dental Clinic",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT019/IBGWTCT019TMPL005/index.html",
  },
  {
    id: 92,
    title: "HomeoPathy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL001/index.html",
  },
  {
    id: 93,
    title: "HomeoPathy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL002/index.html",
  },
  {
    id: 94,
    title: "HomeoPathy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL003/index.html",
  },
  {
    id: 95,
    title: "HomeoPathy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL004/index.html",
  },
  {
    id: 96,
    title: "HomeoPathy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT020/IBGWTCT020TMPL005/index.html",
  },
  {
    id: 97,
    title: "Ayurveda",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL001/index.html",
  },
  {
    id: 98,
    title: "Ayurveda",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL002/index.html",
  },
  {
    id: 99,
    title: "Ayurveda",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL003/index.html",
  },
  {
    id: 100,
    title: "Ayurveda",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL004/index.html",
  },
  {
    id: 101,
    title: "Ayurveda",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT021/IBGWTCT021TMPL005/index.html",
  },
  {
    id: 102,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL001/index.html",
  },
  {
    id: 103,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL002/index.html",
  },
  {
    id: 104,
    title: "Builder",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL002/index.html",
  },
  {
    id: 105,
    title: "Builder",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL003/index.html",
  },
  {
    id: 106,
    title: "Builder",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL004/index.html",
  },
  {
    id: 107,
    title: "Builder",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT014/IBGWTCT014TMPL005/index.html",
  },
  {
    id: 108,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL003/index.html",
  },
  {
    id: 109,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL004/index.html",
  },
  {
    id: 110,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL005/index.html",
  },
  {
    id: 111,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL006/index.html",
  },
  {
    id: 112,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL009/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL009/index.html",
  },
  {
    id: 113,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL0010/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL0010/index.html",
  },
  {
    id: 114,
    title: "Catering",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT023/IBGWTCT023TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT023/IBGWTCT023TMPL001/index.html",
  },
  {
    id: 115,
    title: "Catering",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT023/IBGWTCT023TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT023/IBGWTCT023TMPL002/index.html",
  },
  {
    id: 116,
    title: "Catering",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT023/IBGWTCT023TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT023/IBGWTCT023TMPL003/index.html",
  },
  {
    id: 117,
    title: "Water Sports",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL001/index.html",
  },
  {
    id: 118,
    title: "Water Sports",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL002/index.html",
  },
  {
    id: 119,
    title: "Water Sports",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL003/index.html",
  },
  {
    id: 120,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL001/index.html",
  },
  {
    id: 121,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL002/index.html",
  },
  {
    id: 122,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL003/index.html",
  },
  {
    id: 123,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL004/index.html",
  },
  {
    id: 124,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT025/IBGWTCT025TMPL005/index.html",
  },
  {
    id: 125,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL001/index.html",
  },
  {
    id: 126,
    title: "Water Sports",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL004/index.html",
  },
  {
    id: 127,
    title: "Water Sports",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL007/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL007/index.html",
  },
  {
    id: 128,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL007/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL007/index.html",
  },
  {
    id: 129,
    title: "Wedding Services",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL008/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT022/IBGWTCT022TMPL008/index.html",
  },
  {
    id: 130,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL002/index.html",
  },
  {
    id: 131,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL003/index.html",
  },
  {
    id: 132,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL004/index.html",
  },
  {
    id: 133,
    title: "Music",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT026/IBGWTCT026TMPL005/index.html",
  },
  {
    id: 134,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL004/index.html",
  },
  {
    id: 135,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL005/index.html",
  },
  {
    id: 136,
    title: "Water Sports",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT0241TMPL005/index.html",
  },
  {
    id: 137,
    title: "Water Sports",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT024/IBGWTCT024TMPL006/index.html",
  },
  {
    id: 138,
    title: "Hospitals",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT017/IBGWTCT017TMPL006/index.html",
  },
  {
    id: 139,
    title: "Fashion",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL005/index.html",
  },
  {
    id: 140,
    title: "Fashion",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL006/index.html",
  },
  {
    id: 141,
    title: "Boutique",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL005/index.html",
  },
  {
    id: 142,
    title: "Boutique",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL006/index.html",
  },
  {
    id: 143,
    title: "Boutique",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL007/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL007/index.html",
  },
  {
    id: 144,
    title: "Boutique",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL008/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT028/IBGWTCT028TMPL008/index.html",
  },
  {
    id: 145,
    title: "Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL001/index.html",
  },
  {
    id: 146,
    title: "Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL002/index.html",
  },
  {
    id: 147,
    title: "Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL003/index.html",
  },
  {
    id: 148,
    title: "Fashion",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL001/index.html",
  },
  {
    id: 149,
    title: "Fashion",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL002/index.html",
  },
  {
    id: 150,
    title: "Fashion",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL003/index.html",
  },
  {
    id: 151,
    title: "General",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT030/IBGWTCT030TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT030/IBGWTCT030TMPL001/index.html",
  },
  {
    id: 152,
    title: "Education",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT031/IBGWTCT031TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT031/IBGWTCT031TMPL001/index.html",
  },
  {
    id: 153,
    title: "Sports Academy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL001/index.html",
  },
  {
    id: 154,
    title: "Sports Academy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL002/index.html",
  },
  {
    id: 155,
    title: "Sports Academy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL003/index.html",
  },
  {
    id: 156,
    title: "Sports Academy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL004/index.html",
  },
  {
    id: 157,
    title: "Sports Academy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL005/index.html",
  },
  {
    id: 158,
    title: "Sports Academy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL006/index.html",
  },
  {
    id: 159,
    title: "Sports Academy",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL009/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT032/IBGWTCT032TMPL009/index.html",
  },
  {
    id: 160,
    title: "Coaching Centers",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT033/IBGWTCT033TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT033/IBGWTCT033TMPL001/index.html",
  },
  {
    id: 161,
    title: "Training Institute",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT034/IBGWTCT034TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT034/IBGWTCT034TMPL001/index.html",
  },
  {
    id: 162,
    title: "Kinder Garten",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT035/IBGWTCT035TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT035/IBGWTCT035TMPL001/index.html",
  },
  {
    id: 163,
    title: "Kinder Garten",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT035/IBGWTCT035TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT035/IBGWTCT035TMPL002/index.html",
  },
  {
    id: 164,
    title: "Kinder Garten",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT035/IBGWTCT035TMPL003/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT035/IBGWTCT035TMPL003/index.html",
  },
  {
    id: 165,
    title: "Kinder Garten",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT035/IBGWTCT035TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT035/IBGWTCT035TMPL004/index.html",
  },
  {
    id: 166,
    title: "School",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT036/IBGWTCT036TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT036/IBGWTCT036TMPL001/index.html",
  },
  {
    id: 167,
    title: "School",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT036/IBGWTCT036TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT036/IBGWTCT036TMPL002/index.html",
  },
  {
    id: 168,
    title: "College",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT037/IBGWTCT037TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT037/IBGWTCT037TMPL001/index.html",
  },
  {
    id: 169,
    title: "College",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT037/IBGWTCT037TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT037/IBGWTCT037TMPL002/index.html",
  },
  {
    id: 170,
    title: "Universities",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT038/IBGWTCT038TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT038/IBGWTCT038TMPL001/index.html",
  },
  {
    id: 171,
    title: "Students",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT039/IBGWTCT039TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT039/IBGWTCT039TMPL001/index.html",
  },
  {
    id: 172,
    title: "Students",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT039/IBGWTCT039TMPL002/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT039/IBGWTCT039TMPL002/index.html",
  },
  {
    id: 173,
    title: "Trustee",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL001/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT040/IBGWTCT040TMPL001/index.html",
  },
  {
    id: 174,
    title: "Fashion",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT027/IBGWTCT027TMPL004/index.html",
  },
  {
    id: 175,
    title: "Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL004/index.html",
  },
  {
    id: 176,
    title: "Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL005/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL005/index.html",
  },
  {
    id: 177,
    title: "Business",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL006/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT029/IBGWTCT029TMPL006/index.html",
  },
  {
    id: 178,
    title: "Hotels",
    img: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL004/home.jpg",
    price: "$5.50",
    live: "https://www.webtekdi.com/website/buynow/templates/IBGWTCT003/IBGWTCT003TMPL004/index.html",
  },
];

export const Domains = [
  {
    label: ".com",
    value: ".com",
  },
  {
    label: ".in",
    value: "in",
   
  },
  {
    label: ".org",
    value: ".org",
   
  },
  { label: ".net", value: ".net" },
 
  {
    label: ".ind.in",
    value: ".ind.in",
  },
  {
    label: ".co.in",
    value: ".co.in",
 
  },
 
];
